alias ..="cd .."
alias ls="ls --color=auto"
alias l="ls --color=auto"
alias la="ls -a"
alias v="xclip -o"
alias c="xclip"
alias clip="c -sel clip"
alias mp="markdown_previewer"
alias jsontool="py -m json.tool"
alias pip="py -m pip"
alias vi="vim"
