alias ..="cd .."
alias ls="ls --color=auto"
alias l="ls --color=auto"
alias la="ls -a"
alias v="xclip -o"
alias c="xclip"
alias clip="c -sel clip"
alias tsm="transmission-remote"
alias mp="markdown_previewer"
alias torrents="watch --interval 5 'transmission-remote -l'"
alias jsontool="py -m json.tool"
alias vi="vim"
alias notebook="jupyter notebook"
alias gpg="gpg2"
