set encoding=utf-8
scriptencoding utf-8
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

"ctrl-p
Plugin 'https://github.com/kien/ctrlp.vim.git'

"NERDTree
Plugin 'https://github.com/scrooloose/nerdtree.git'

"vim-airline
Plugin 'https://github.com/vim-airline/vim-airline.git'
Plugin 'vim-airline/vim-airline-themes'

" vim-fugitive
Plugin 'https://github.com/tpope/vim-fugitive.git'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
" ========================================="


" AIRLINE

set laststatus=2	"Show airline
set ttimeoutlen=50

let g:airline#extensions#tabline#enabled = 1
let g:Powerline_symbols = 'fancy'
let g:airline_theme='badwolf'

" AIRLINE FONTS
" Need to install fonts from https://github.com/powerline/fonts/archive/master.zip
" let g:airline_powerline_fonts = 1  " Needs to install fonts


" REGULAR CONFIG

syn on se title		"Syntax highlighting on and show the file name in the terminal title bar
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
set autoread	" Automatically reload file as soon as it changes on disk
"set hidden		" Hide buffers when they are abandoned
set mouse=v		" Enable mouse usage
set background=dark
set t_Co=256		"Set colors

set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab
set autoindent
set smartindent
"hidden characters
"set listchars=eol:¬,tab:>-,trail:·,extends:>,precedes:<
"set list

set number relativenumber

set clipboard=unnamed

" Alias
command NT NERDTree
command Q q!
command W wall

" Snippets
nnoremap ,head :0read! sed -n '1,2p' ~/.vim/snippets.py<CR>
nnoremap ,with :-1read!  sed -n -e '/with/,/closed/p' ~/.vim/snippets.py<CR>
nnoremap ,for :-1read! sed -n -e '/for v/,/pass/p' ~/.vim/snippets.py<CR>
nnoremap ,fkv :-1read! sed -n -e '/for k/,/pass/p' ~/.vim/snippets.py<CR>
nnoremap ,[for :-1read! sed -n -e '/x/,/$/p' ~/.vim/snippets.py<CR>
nnoremap ,main :-1read! sed -n -e '/__name__/,/$/p' ~/.vim/snippets.py<CR>
nnoremap ,ipdb :-1read! sed -n -e '/import/,/$/p' ~/.vim/snippets.py<CR>
